---
# Not sensitive: the identity ID only works with a valid token from this
# cluster's external-secrets ServiceAccount.
apiVersion: v1
kind: Secret
metadata:
  name: infisical-kubernetes-auth
stringData:
  identityId: f5e97849-036e-40b3-b9c8-97f79909f81f
