---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: cloudflare-dns-secret
  data:
    - secretKey: CF_API_TOKEN
      remoteRef:
        key: /cloudflare-dns/CF_API_TOKEN
    - secretKey: CF_ZONE_ID
      remoteRef:
        key: /cloudflare-dns/CF_ZONE_ID
