apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:EbLbdsImaqKELv4AfF7iD3KwS+2S,iv:WgE4/daK5iUuznRjSH9791DhIxcULI8G3oxdrseQxKE=,tag:j57Tgo/zA2SL/VvyBLz40A==,type:str]
  WAN_IP: ENC[AES256_GCM,data:Di5M0tvcVKjr6CQVUw==,iv:Wv1eLPUJ01gduI6TlPkP/glTi4PHXFADnldjTHrtDno=,tag:KBbG3WGQLN/Y0IsXruIvpw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5ICtzakFWRFBs
        VVBGTC9pNGtsM2RGYWVTeVFuZGtNQ1RuMC9lb3Q5Z3FGdkg1cGZGbzVEVWowaUg5
        QldHU3BSRlhYNnQ4em1meUdkLys1Ym9nTGIzcXVaeUVVY1I2YlNoZW53NjdmNEVn
        eUpiWGxWSlpMM0wrcU5nenRGTzZBZmNXci8yb0pSdnd3cEttaUdycmdnM2FxOFdY
        OXlsUGNaN00ybVd5OFdKMDFkT1hGU0twem9GNFdSR2c3MlBIYngyd0h0SVMvZy9L
        cVc1MzFBTlUxL2F2aG5LQ08vc0hXVmc4OXlaN2F6MWZLOE1ENitieUhtL3ZIcjdu
        Slh1KzZCWGRIQlQ5akNIb29ESHY5bGUzZGkvZ05JZVdsZ04vWkUwOEhoU0xya1Vj
        c1hLV0ZSS212WmM0bFVZeUhzVzRodEFjZnNEajQ1SEVFOUxYYnM1S0FPUERZdlps
        d1l6Nlhqdkg3R0xwdmpXVXdPWHBiTjR5VzNlY1c3ZmVKZXZXMzk4ckFFVWtWYk9J
        UXhVOXEvUW1ucFBEYk9PWjJKTXpram5abElpZXc2dXZtTWR6YUJVdnRiYmo1YTd2
        NXJtMUtheitNeW5CZWF4clFyd1haSlh2UUVyVHNlaUNqVnVyb3B2SjVnWi9kTURx
        Rms2UmszSXZEeGhOYkNzT293TTMvOFhQU2Eza1plVldFRHFUMExtUVNRYWw1NFY0
        L2pZTUVJSTlhS1F4NXJtczF6N1Jtbllla2d1WTI3Q3R5WEh0Q2ZRZkhyMmJBYm42
        anVUcmRwY0Vhc2ZBLytLZ0d4dXFjdnJEVjB2bmtzczYrOEtxVWRTS3VRL1ZBRStu
        M2MvYUZMWmROb1loRi9wM1ZFYm5mbEJPcGdjakFzR1BQSVJuSGp4QVVSblFyaks4
        MFFMN1VTV1JQTUZsNTZhYVhVOE9JUmgrSFBmbFJmSEJYTzE5T09ZTTV2K3F5Z3dv
        VW5RcFk1a054eW9CRFdCTHU1WkxwOFhLaDY5MUxhQW8reExsSW52aE5MV1MxQTVB
        Z1VsanNjSGtObXRCRWdUVUVubGhnZEphYlNtQ2ZhaWJuVGl2aFNIRGRmYlplNkpi
        SmR6emhTQituL1ZSSHFVN2xFR1cwMGh6T0YwS1lPdjY3U1dUazJrSDVtUVFZc2Zm
        VkhOVGJuV05XV3BIcThwRXc3S1g1bzFEQUtvblcrNm1QUnhrK2dHcEpHY1RzR0pQ
        MW1DcW1haWJGL0t4MEM1cUN5ZUFQcFVlSGxiNWUvdXN0VU1UZlZUKzlEZlNkQnR1
        YjNpaC9neU9qYU9BNFNwcEFnaDd5VSs2QU5Zb09QaWhDUlVYNk5EWHpwQ1lTZGxC
        QmxvZG1rTUlxSVlXd0V4dUdRZkV2eitvNzZyRjZlbjdBRVg5UWFQemlHWDFBc1pj
        YjVqT3FSZ2NKdEw4WERsTnViUDVDRkpvY2tUMGYreDlxRHk2ajVHSzJxT1ZjL3pR
        dS9zcHpub0JETXVLMk45RHV2d2tBT3pkNm96Z25CZmxUS1J5aUU1LzBkdDlWckZF
        OGgxYU95YVJ6Z3VlSWtrTXZDZnZoclQ1cTdob3Y5OUxkdmNIUTBjd25PcXhiUzlq
        MW1hUVZ3aEdQVDE1eG5mOG1hN1JDS2ticVYrbC8zNDJyeEx3dGV3OHExNCtOYXEz
        VFNBdy9qRmM0MDRJdzArNWFBb01TdWhUVlRyWWdQdHYzN2RnaTFpNmV1MVZJbk4w
        R3hRNm1aQVNOQituU3pNbGdzZE1Hc1dvOGpEMDdsdWlvOXB2YlhVY0VOdGlJdEFP
        ZWNBamxMbEhudEJZNk53NTYxL3BQcTF2QjBQNnRSQVhEQitGUnZmclh4U0k0enF1
        dTc2SkExZkFFT0NDR1k3aGFsVWpwalFOMXVUY3ZVTWF6dlhtbmxvZjRBRnB1SStO
        VW1LZi9DTFl0dTVocjl0SGM1QitLYXMwMHNoZTk0aGJmY2tYeDdUeVJKdHdhUQp0
        ZW5sSnE4S1hNRFdQbzdJRjFady9aT1N1MWxFMXlaR0tTQ2M4VTY1cGFRCi0tLSAz
        VkppL0dvbndoZDhseHB1WkNrVlFxaXRHUEpEWVdLWVNJbGoxQlB1V1pJCt9S1riu
        ZtUCNKimeU6UOKCR1NvH3HVe5hAYVwHn0wuvvxR3IAPUhrVlgJ7l4JkKsSvEMT4V
        IgwI3rzzGgUkSFI=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq175fnl9q29fwssjka6emkl7926rgjy3ezp9kngxyw69v2dvf0fuu947tzrvkrkj77rd8sd9dkhjv87mr6rm3yvec0q8yyfjnxucn98m0j5dfjyyqwtygt5wqnxytpqpn4y0k4jxsqk9cnv2ysv8yhngf6c9p556cgyssvmvgkczdxcr0v25u5sukeyzp68ca3kgn97l5spy0ej8dwm9gfkstxml6rmxq204h0hg9ejaelmwc6n5eg0vj8gu5fx950xsrqp2kg6trzf8m83tfl3zkv4xwqvpz7q7chaq9sgsmyxcnun8yhhkar4xtm0jstjqg2z9sf3sjj079962qrksuqq778sy00u2f55qvl0ccj2ruhkxl5qhfcyhpr9ed7uz3vgeaks9ccx2t4r26ak2qxfqm6v8m2npe2zwrt3fqp22uvjefsmaashljk02sqqapmv6kwyk62quszrnak30xhlxxvtkcl2gqhy6vsdpmm38kfz6tp3ajz5takl7dsz4v60s82z4xj2z6hw36pnjj8y0c0wlnsvgterka0m2dhsf9xcmlzdjcsdy674ecezhqy6azpveegf08n2z2wq6jq0c9q5a58pwlx9q8hlvqvjxrfmrsk06t2v3982aqwca0th89kt0m8zsnxqnjqetttckznd9ac4yuupa8rn7cd5f2w8ps8mc9yece2fhwrp8hn8tjg7mz9yqxxtwpyk2y9y9v8vm64897fscypzvc8eu3pzp7etyuezfd34sdwm5ug0uay8cx5f0v3w24kpt98z2cz8ljtnw57qr6w7973554astcrmax3dq90tf3cvqsfaesz0n6ztu520fshj65h6x4y38qzc7ue5dc82jdjgje6zc0hl4yt9dgpv80cp35phdtd9zle24ewd0gx22gpqqsvsapnq7xs0fyuze95swkheze599y6wzup4e27zvju7npqwlk89vmzzssqsf3853std7xq5chcnnee2sk3ak7vrftzf9fzdy4ukecvd26466ccvzecq2chzx6uf3llkx9f7q9jsrncphvnyn2acf6vfqkahj7fzu3qgyhzvh22krncsz48vf4pu39gq4tvzy92clystqsdqzvz6we9pgczk25y42zzaqmdv9v52efejnexqv4dj0hfvkhlxxfrenmrrnf28gdvn9hcd9qyu3zh6yvq7ga3e35agm9u5csqzt9j9dfctyqfepepg2uyk9vfdfat0p5kqhs6n9mk9v4xkjw0ke3tr2dckcnedlqegxzy73lnhyvj4eg95kdhevkhjygl33v99jnq7knygctmdl4857v9rfzyae3eykaqhu8ss3vkj60s28zlapfny64ha5dre5gnjph7ejc06fxp3gaxp42nx7nv8pqx42tnccje9xy22v569ltkz4g2afwepvtztrsye2d80xw9pfepyuhvr2e4trnc9py6t86nr9gn565mf2kqffr463qzec8ag4rmdyak056xf7zs78r3kk5uke299vnpj7phn9zs9fwjjspedt9escrdgl9eqmsqa20446frrv9dceyycsjske2xwj349pdsw6agqul56c3u9z65je89r6eunytdyvcteud3ktkz050cedn63t9t9yh9nzqamcncknu6j2yl5xngs88jme966g4x9tag5d2x53fkvg07u5jcqfnghdev2jtt8xd3lqcqd4unvdmpgfjt9l7xjnnmck47yju23z7gnvwfgrtn284cz5laz9qajjymdgyhz36twmfsqzdhhz5twmkv32qxymsj0tu0skggfsmgtywgrpacxg5fk76p0zr8smhh8dhct3j8pykw6vevnsxf8vy9lg9rmql6raawtg0nh7ph6n8yxt9sd0ge9ws7pgsg2wc354k060amuwd9wjrxylxvf4ks6539psjk3vmm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T06:53:17Z"
  mac: ENC[AES256_GCM,data:+NMNJzEBoS1RaeUKFXyWYuu5jhpM0/zeioG+kDmskYLsDcYdwlkow8y2cmwY9xd9lHMf7Py7VU/nF9MLonWOHDM7rgXWaLFv2g3KWSjQ7pk8y4VH8sK1BfMgd0SnR8sa5wjsN2bQmXtOHWjji/5Nn2V+AR94JxEl80MBWU/iY5A=,iv:WHcIi+CTXt++5H+Qw4gr2sIovHARJ69CHsHTK54CJHg=,tag:SR/9W9/IYr4OP1sU3FCl6A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
