---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-dns
spec:
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cloudflare-dns
      namespace: network
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: dnsendpoints.externaldns.k8s.io
  interval: 1h
  path: ./kubernetes/apps/network/cloudflare-dns/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
---
# Separate so the DNSEndpoint CRD (installed by the chart) exists first
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-dns-endpoint
spec:
  dependsOn:
    - name: cloudflare-dns
  interval: 1h
  path: ./kubernetes/apps/network/cloudflare-dns/endpoint
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
