---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: technitium-dns-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: technitium-dns-secret
  data:
    - secretKey: EXTERNAL_DNS_RFC2136_TSIG_SECRET
      remoteRef:
        key: /technitium-dns/EXTERNAL_DNS_RFC2136_TSIG_SECRET
