---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radar-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: radar-secret
  data:
    - secretKey: client-secret
      remoteRef:
        key: /radar/OIDC_CLIENT_SECRET
    - secretKey: auth-secret
      remoteRef:
        key: /radar/AUTH_SECRET
